account/urls.py
from django.urls import path
from .views import register__view, login__view, logout__view
app_name = "account"
urlpatterns = [
    path("register", register__view, name="register"),
    path("login", login__view, name="login"),
    path("logout", logout__view, name="logout"),
    
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from article.views import *

urlpatterns = [
    path("", home__view, name="home"),
    path("about/", about__view, name="about"),
    path("articles", articles, name="articles"),
    path("dashboard", dashboard, name="dashboard"),
    path("add_article", add_article, name="add_article"),
    path("article_detail/<int:id>", article_detail, name="article_detail"),
    path("contact", contact__view, name="contact"),
    path("account/", include("account.urls")),
    path('admin/', admin.site.urls),
]

account/models.py
from django.db import models

# Create your models here.

article/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    author = models.ForeignKey("auth.User", on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    content = models.TextField(max_length=500)
    created_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f"{self.title} | {self.author}"

account/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(max_length=20, label="USERAME")
    password = forms.CharField(max_length=10, label="PASSWORD", widget=forms.PasswordInput)
    

class RegisterForm(forms.Form):
    username = forms.CharField(max_length=20, label="USERNAME")
    password = forms.CharField(max_length=10, label="PASSWORD", widget = forms.PasswordInput)
    confirm = forms.CharField(max_length=10, label="PASSWORD CONFIRM", widget = forms.PasswordInput)
    
    def clean(self):
        try:
            username = self.cleaned_data["username"]
            password = self.cleaned_data["password"]
            confirm = self.cleaned_data["confirm"]

            if password and confirm and password != confirm:
                raise forms.ValidationError("Şifrələr eyni deyil!")

            values = {
                "username": username,
                "password": password
            }

            return values

        except KeyError as e:
            raise forms.ValidationError(f"Missed Fields: {e.args[0]}")
        except Exception as e:
            raise forms.ValidationError(f"An error occurred: {str(e)}")

article/forms.py
from django import forms
from .models import Article
class ArticleForm (forms.ModelForm):
    
    class Meta:
        model = Article
        fields = ("title", "content")

account/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm, LoginForm
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.db import IntegrityError


def register__view(request):
    form = RegisterForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
        
            try:
                newUser = User(username=username)
                newUser.set_password(password)
                newUser.save()
                login(request, newUser)
                messages.success(request, "Siz qeydiyyatdan keçdiniz.")
                return redirect("home")
            except IntegrityError:
                messages.error(request, "Bu istifadəçi adı artıq mövcuddur. Zəhmət olmasa başqa bir istifadəçi adı seçin.")
            except Exception as e:
                messages.error(request, f"Qeydiyyat zamanı bir xəta baş verdi: {e}")
    
    context = {
        "form": form,
    }
    return render(request, "register.html", context)

def login__view(request):
    form = LoginForm(request.POST or None)
    
    context = {"form": form}
    
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        
        user = authenticate(username=username, password=password)
        
        if user is None:
            return render(request, "login.html", context)
        
        login(request, user)
        messages.success(request, "Siz daxil oldunuz.")
        return redirect("home")
    return render(request, "login.html", context)


def logout__view(request):
    logout(request)
    return redirect("home")

article/views.py
from django.shortcuts import render, redirect
from .models import Article
from .forms import ArticleForm
from django.contrib import messages

# Create your views here.
def home__view(request):
    return render(request, "index.html")

def articles(request):
    articles = Article.objects.all()
    return render(request, "articles.html", {'articles' : articles})

def add_article(request):
    form = ArticleForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        # save() -> hemise commiti True olaraq qebul edir.
        messages.success(request, "Article is added.")
        return redirect("dashboard")
    context = {"form" : form}
    return render(request, "add_article.html", context)

def dashboard(request):
    articles = Article.objects.filter(author = request.user)
    return render(request, "dashboard.html", {'articles' : articles})

def about__view(request):
    return render(request, "about.html")

def contact__view(request):
    return render(request, "contact.html")

def article_detail(request, id):
    article = Article.objects.filter(id=id).first()
    context = {"article" : article}
    return render(request, "article_detail.html", context)

templates/about.html
{% extends "base.html" %}
{% block page__title %}
    About Page
{% endblock page__title %}
{% block body %}
   <h2>About Page</h2>
{% endblock body %}

templates/add_article.html
{% extends "base.html" %}
{% block page__title %}
   Add Article
{% endblock page__title %}
{% block body %}
   <h2>ADD ARTICLE</h2>
   <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.media}}
    {{form.as_p}}
    <br>
     <button class="btn">ADD</button>
    </form>
{% endblock body %}

templates/article_detail.html
{% extends "base.html" %}
{% block page__title %}
   Article Detail Page
{% endblock page__title %}
{% block body %}
   
   <div class="articles">
   <ul>
       <li>
        <h3>{{article.author}}</h3>
        <h4>{{article.title}}</h4>
        <p>{{article.content}}</p>
        <small>{{article.created_date}}</small>
      </li>
      <hr>
    </div>
{% endblock body %}

templates/articles.html
{% extends "base.html" %}
{% block page__title %}
   Articles Page
{% endblock page__title %}
{% block body %}
   
   <div class="articles">

   <ul>
     {% for article in articles %}
       <li>
        <h3>{{article.author}}</h3>
        <h4>{{article.title}}</h4>
        <p>{{article.content}}</p>
        <small>{{article.created_date}}</small>
      </li>
      <hr>
    {% endfor %}
{% endblock body %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=content-width, initial.scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static "style.css" %}">
    <title>
        {% block page__title%}
            MY SITE
        {% endblock page__title%}
    </title>
</head>
<body>
    <div class = "navbar">
        <div class = "navlogo">
            <img src="{% static 'book.jpg' %}" alt="">
        </div>
        <div class = "navlink">
            <ul>
                <li><a href="{% url 'home' %}">HOME</a></li>
                <li><a href="{% url 'about' %}">ABOUT</a></li>
                <li><a href="{% url 'contact' %}">CONTACT</a></li>
            {% if request.user.is_authenticated %}
            <li><a href="{% url 'articles' %}">ARTICLES</a></li>
            <li><a href="{% url 'dashboard' %}"><i class="fa-solid fa-user"></i></a></li>
            <li><a href="{% url 'account:logout' %}"><i class="fa-solid fa-right-from-bracket"></i></a></li>
                </div>
            {% else %}
                <li><a href="{% url 'account:login' %}">LOGIN</a></li>
                <li><a href="{% url 'account:register' %}">REGISTER</a></li>   
            {% endif %}  
            </ul>
        </div>
    </div>
    <div class = "container">
    {% block body %}
      
    {% endblock body %}
    </div> 
</body>
</html>

templates/contact.html
{% extends "base.html" %}
{% block page__title %}
   Contact Page
{% endblock page__title %}
{% block body %}
   <h2>Contact Page</h2>
{% endblock body %}

templates/dashboard.html
{% extends "base.html" %}
{% block page__title %}
   My Articles Page
{% endblock page__title %}
{% block body %}
{% if messages %}
   {% for message in messages %}
     {% if message.tags == "error" %}
        <div class="alert__eror">{{message}}</div>
        {% else %}
        <div class="alert__success">{{message}}</div>
        {% endif %}  
   {% endfor %}
{% endif %}
{% if request.user.is_authenticated %}
 <div class="user_info">
  <h2>Xoş gəlmisiniz, 
   <span> {{request.user.username}} </span></h2>
 </div>
{% else %}
<div class="user_info">
  <h2>Daxil olmamısınız.</h2>
 </div>
{% endif %}  
   
<div class="articles">
   <ul>
       
       {% for article in articles %}
           <li>
               <h3>{{article.author}}</h3>
               <h4><a href="{% url 'article_detail' article.id %}">{{article.title}}</a></h4>
                <p>{{article.content|safe|truncatechars:70}}</p>
               <small>{{article.created_date}}</small>
               <br>
           </li>
           <br>
           <hr>
           <br>
       {% endfor %}
   </ul>
</div>

<br>
<a href="{% url 'add_article' %}"><button class="btn">ADD ARTICLE</button></a>
{% endblock body %}

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block page__title %}
   Home Page
{% endblock page__title %}
{% block body %}

{% if messages %}
   {% for message in messages %}
     {% if message.tags == "error" %}
        <div class="alert__eror">{{message}}</div>
        {% else %}
        <div class="alert__success">{{message}}</div>
        {% endif %}  
   {% endfor %}
{% endif %}

{% endblock body %}

templates/login.html
{% extends "base.html" %}

{% block page__title %}
    Login Page
{% endblock page__title %}

{% block body %}
    <h2>Login Page</h2>

    <form method="post">
        {% csrf_token %}
        <div class="form_group">
            <label for="{{form.username.id_for_label}}">İstifadəçi adı</label>
            {{form.username}}
        </div>
        <div class="form_group">
            <label for="{{form.password.id_for_label}}">Şifrə</label>
            {{form.password}}
        </div>
        <br>
        <button class="btn">Daxil ol</button>
    </form>
{% endblock body %}
    

templates/my__articles.html
{% extends "base.html" %}
{% block page__title %}
   My Articles Page
{% endblock page__title %}
{% block body %}
   
   <div class="articles">
      <h2>My Articles</h2>
   <ul>
    {% for article in articles %}
       <li>
        <h3>{{article.author}}</h3>
        <h4>{{article.title}}</h4>
        <p>{{article.content}}</p>
        <small>{{article.created_date}}</small>
      </li>
      <hr>
    {% endfor %}
{% endblock body %}

templates/our__articles.html
{% extends "base.html" %}
{% block page__title %}
   Our Articles Page
{% endblock page__title %}
{% block body %}
   
   <div class="articles">
    <h2>Our Articles</h2>
   <ul>
     {% for article in articles %}
       <li>
        <h3>{{article.author}}</h3>
        <h4>{{article.title}}</h4>
        <p>{{article.content}}</p>
        <small>{{article.created_date}}</small>
      </li>
      <hr>
    {% endfor %}
{% endblock body %}

templates/register.html
{% extends "base.html" %}

{% block page__title %}
    Register Page
{% endblock page__title %}

{% block body %}
    <h2>Register Page</h2>

    <form method="post">
        {% csrf_token %}
        <div class="form_group">
            <label for="{{form.username.id_for_label}}">İstifadəçi adı</label>
            {{form.username}}
        </div>
        <div class="form_group">
            <label for="{{form.password.id_for_label}}">Şifrə</label>
            {{form.password}}
        </div>
        <div class="form_group">
            <label for="{{form.confirm.id_for_label}}">Şifrəni Təsdiqlə</label>
            {{form.confirm}}
        </div>
        <br>
        <button class="btn">Qeydiyyatdan Keç</button>
    </form>
{% endblock body %}